yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorPage.as_view(), name='author'),
    path('tech/', views.AboutTechPage.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group, name='group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_details'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_update'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
]

yatube/users/urls.py
from django.contrib.auth import views
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

from .views import SignUp


app_name = 'users'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path(
        'login/',
        views.LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'logout/',
        views.LogoutView.as_view(
            template_name='users/logged_out.html',
        ),
        name='logout'
    ),
    path('password_change/', views.PasswordChangeView.as_view
         (template_name='users/password_change_form.html'),
         name='password_change_form'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view
         (template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', views.PasswordResetView.as_view
         (template_name='users/password_reset_form.html',
          email_template_name='users/password_reset_email.html',
          success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset_form'),
    path('password_reset/done/',
         login_required(views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html',
         )),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view
         (template_name='users/password_reset_confirm.html',
          success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('password_reset/complete/',
         login_required(views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html',
         )),
         name='password_reset_complete'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
]

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube and <span style="color:red">k</span>92</p>
</footer>

yatube/templates/includes/head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
<link rel="icon" type="image/png" sizes="192x192" href="{% static 'img/fav/android-chrome-192x192.png' %}">
<link rel="icon" type="image/png" sizes="256x256" href="{% static 'img/fav/android-chrome-256x256.png' %}">
<link rel="icon" type="image/png" sizes="150x150" href="{% static 'img/fav/mstile-150x150.png' %}">
<meta name="msapplication-TileColor" content="#000">
<meta name="theme-color" content="#ffffff">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
        <a href="{% url 'about:author' %}">Об авторе</a>
        <a href="{% url 'about:tech' %}">О сайте</a>
            {% if user.is_authenticated %}
                <a href="{% url 'posts:post_create' %}">Создать публикацию</a>
                <a href="{% url 'posts:profile' user.username %}">Мой профиль</a>
                <a href="{% url 'users:logout' %}">Выйти</a>
            {% else %}
                <a href="{% url 'users:login' %}">Войти</a>
                <a href="{% url 'users:signup' %}">Регистрация</a>
            {% endif %}
        </a>
    </div>
</nav>