yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorPage.as_view(), name='author'),
    path('tech/', views.AboutTechPage.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group, name='group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_details'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_update'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from . import settings


User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Группа',
        help_text='Название группы',
    )
    slug = models.SlugField(
        max_length=30,
        unique=True,
        verbose_name='Короткий адрес',
        help_text='Короткий идентификатор группы',
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Текстовое описание группы',
    )

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст',
        help_text='Текстовое содержимое публикации',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
        help_text='Дата публикации поста',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Имя создателя публикации',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Имя группы для публикаций',
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

    def __str__(self):
        return self.text[:settings.SELF_TEXT_LENGTH]

yatube/posts/forms.py
from django import forms

from .models import Post
from . import settings


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        exclude = ('author',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            self.fields[field].help_text = None

    def clean_text(self):
        data = self.cleaned_data['text']
        if len(data) < settings.TEXT_LENGTH_MINIMAL:
            raise forms.ValidationError('Текст публикации не может быть короче'
                                        ' 10 символов.')
        return data

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import PostForm
from .models import Post, Group, User
from .utils import paginate_page


def index(request):
    posts = Post.objects.select_related('author', 'group')
    page_obj = paginate_page(request, posts)
    return render(request, 'posts/index.html', {
        'page_obj': page_obj,
    })


def group(request, slug):
    group = get_object_or_404(Group, slug=slug)
    group_posts = group.posts.select_related('author')
    page_obj = paginate_page(request, group_posts)
    return render(request, 'posts/group_list.html', {
        'group': group,
        'posts': group_posts,
        'page_obj': page_obj,
    })


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related('group')
    page_obj = paginate_page(request, post_list)
    context = {
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post.objects.select_related('group'), id=post_id)
    context = {
        'post': post,
    }
    return render(request, 'posts/post_details.html', context)


@login_required
def post_create(request):
    post = Post.objects.select_related('author')
    form = PostForm(request.POST or None)
    if form.is_valid():
        post_item = form.save(commit=False)
        post_item.author = request.user
        post_item.save()
        return redirect('posts:profile', post_item.author)

    return render(
        request,
        'posts/create_post.html',
        {'post': post, 'form': form}
    )


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        messages.error(request, 'Вы не можете редактировать чужие публикации!')
        return redirect('posts:post_details', post_id)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_details', post_id)
    return render(
        request,
        'posts/create_post.html',
        {'post': post, 'form': form, 'is_edit': True},
    )


@login_required
def post_delete(request, post_id):
    post = Post.objects.get(id=post_id)
    if request.user == post.author:
        post.delete()
        return redirect('posts:index')
    messages.error(request, 'Вы не можете удалять чужие публикации!')
    return redirect('posts:post_details', post_id)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
    {% if is_edit %}
        Редактировать пост
    {% else %}
        Создать пост
    {% endif %}
{% endblock title %}
{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        {% if is_edit %}
                            Редактировать пост
                        {% else %}
                            Новый пост
                        {% endif %}
                    </div>
                    <div class="card-body">

                        {% if is_edit %}
                            <form id="update-form" method="post" action="{% url 'posts:post_update' post.id %}">
                        {% else %}
                            <form id="add_form" method="post" action="{% url 'posts:post_create' %}">
                        {% endif %}

                        {% csrf_token %}

                        {% if errors %}
                            {% for error in errors %}
                                <div class="alert-danger">{{ error }}</div>
                            {% endfor %}
                        {% endif %}

                        {{ form }}

                        </form>
                        <div class="modal-footer">

                            {% if is_edit %}
                                <button form="update-form" type="submit" class="btn btn-primary">Обновить</button>
                            {% else %}
                                <button form="add_form" type="submit" class="btn btn-primary">Добавить</button>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    <div class="container py-5">
        <h1>{{ group }}</h1>
        <p>{{ group.description }}</p>
        <br>
        {% for post in page_obj %}
            <article>
                <ul>
                    <li>
                        Автор: <a
                            href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
                    </li>
                    <li>
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                </ul>
                <p>
                    {{ post.text }}
                </p>
                <a href="{% url 'posts:post_details' post.id %}">Подробная информация</a>
            </article>
            {% if not forloop.last %}
                <hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
    <div class="container py-5">
        <h2>Последние обновления на сайте</h2>
        <br>
        {% for post in page_obj %}
            <article>
                <ul>
                    <li>
                        Автор: <a
                            href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
                    </li>
                    {% if post.group %}
                        <li>
                            Группа: <a href="{% url 'posts:group' post.group.slug %}">{{ post.group }}</a>
                        </li>
                    {% endif %}
                    <li>
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                </ul>
                <p>
                    {{ post.text }}
                </p>
            </article>
            <button type="button" class="btn btn-primary">
                <a href="{% url 'posts:post_details' post.id %}">
                    <span style="color:white">Подробная информация</span>
                </a>
            </button>
            {% if not forloop.last %}
                <hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/post_details.html
{% extends 'base.html' %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock title %}
{% block content %}
    <div class="container py-5">

        {% if messages %}
            {% for message in messages %}
                <div class="alert-danger">{{ message }}</div>
            {% endfor %}
        {% endif %}

        <ul>
            <li>
                Автор: <a
                    href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
            </li>
            {% if post.group %}
                <li>
                Группа: <a href="{% url 'posts:group' post.group.slug %}">{{ post.group }}</a>
            {% endif %}
            <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            </li>
            <li>
                Всего постов автора: <span>{{ post.author.posts.count }}</span>
            </li>
            <li>
                <a href="{% url 'posts:profile' post.author.username %}">
                    Все посты пользователя
                </a>
            </li>
        </ul>
        <article>
            <p>
                {{ post.text }}
            </p>
        </article>
        {% if post.author == user %}
            <button type="button" class="btn btn-secondary">
                <a href="{% url 'posts:post_update' post.id %}">
                    <span style="color:white">Редактировать</span>
                </a>
            </button>
            <button type="button" class="btn btn-danger">
                <a href="{% url 'posts:post_delete' post.id %}">
                    <span style="color:white">Удалить</span>
                </a>
            </button>
        {% endif %}
    </div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя @{{ author.username }}{% endblock title %}
{% block content %}
    <div class="container py-5">
        <h2>Все посты пользователя {{ author.get_full_name }} </h2>
        <h3>Всего постов: {{ author.posts.count }} </h3>
        <br>
        {% for post in page_obj %}
            <article>
                <ul>
                    {% if post.group %}
                        <li>
                            Группа: <a href="{% url 'posts:group' post.group.slug %}">{{ post.group }}</a>
                        </li>
                    {% endif %}
                    <li>
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                </ul>
                <p>
                    {{ post.text }}
                </p>
                <a href="{% url 'posts:post_details' post.id %}">Подробная информация</a>
            </article>
            {% if not forloop.last %}
                <hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock content %}